### PR TITLE
version 20151021

### PR DESCRIPTION
**Pull request by lightgao**
Hi, Thanks firstly, traveling-ruby help me a lot.

This commit contain a new gem with native extension : blockenspiel, and new version update for existing gems.

I failed to run upload task "linux/rake upload", which asked me to provide access key. So, could you help to build and upload the generated packages?

### CODE REVIEW

**Comment by lightgao** [comment]
## Version 20150517
Added additional native extensions: 
    eventmachine.
Upgraded following gems:
    eventmachine (1.0.8)
    json (1.8.3)
    mysql2 (0.4.1)
    pg (0.18.3)
    redcarpet (3.3.3)
    sqlite3 (1.3.11)
    thin (1.6.4)

**Comment by FooBarWidget** [comment]
Sorry for the late response. I'm planning on looking into it this week.

**Comment by FloorD** [comment]
@lightgao I'm guessing these gems are already outdated. Could we bother you with updating your pull request? Related: we'll do an effort updating Gem support as well as Ruby versions (up to 2.5) support these coming weeks.

**Comment by peters95** [comment]
@FloorD its been a while is there any plans to update the Ruby version to 2.5+ still?

**Pull request closed without merging**
